writeln('Baldi's Basics In Education And Learning');
Sleep(17);
writeln('For DOS!');
 gotoxy(40+j,23-i);
         write('Corrpsus ');
          gotoxy(40+j,23-i);
         write('Crash ');
          gotoxy(40+j,23-i);
         write('CRASH ');
          gotoxy(0+j,0-i);
         write('Oh Hi! Welcome To My Schoolhouse! ');
         gotoxy(0+j,0-i);
         write('1695+7 ');
         gotoxy(0+j,0-i);
         write('72927282+799788 ');
         Paused := True;
Continue.Enabled := True;
while Paused do
begin
  sleep(100);
  Application.ProcessMessages;
end;
gotoxy(0+j,0-i);
         write('Oh Hi! Welcome To My Schoolhouse! ');
         gotoxy(0+j,0-i);
         write('this was a joke okay! ');
